### ISSUE TITLE
Fix Footer CSS

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/activate-rewrite#13]
Currently the footer has some inconsistencies:

- [x] The two borders to separate the logo and the language switcher are not the same
- [x] The Logo and Language switcher are not aligned centered compared to the description
- [x] Footer should always be at the bottom (currently it's not if there is not enough content to fill the height of the screen)
- [x] Better mobile view

**Comment by kelimuttu** [comment]
Should we also add one action to make the footer stays at the bottom of the screen?

**Comment by MichaelKohler** [comment]
Yep, added!

**Comment by kelimuttu** [comment]
Ok. I'll be working on this next.

**Comment by kelimuttu** [comment]
PR sent https://github.com/MichaelKohler/activate-rewrite/pull/25
