### ISSUE TITLE
Prevent Font Loading from flashing

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/activate-rewrite#14]
When reloading the page we first display the fallback font and then once loaded, Zilla Slab Highlight is shown. This is quite a remarkable flash on the screen and we should try to avoid this.

**Comment by kelimuttu** [comment]
So, I found a [link](https://stackoverflow.com/questions/11711641/avoid-delayed-load-of-font-face). It says that based on [this blogpost](https://www.paulirish.com/2009/fighting-the-font-face-fout/), there are 2 ways we can try to "cover" this issue, which is by hiding the component/the page. Might not be the best option, but still worth to try.

**Comment by kelimuttu** [comment]
Aaand, it's only happen in Firefox, btw. Webkit has different approach of serving the font that they hide the font until it's perfectly loaded.

**Comment by MichaelKohler** [comment]
I have a few ideas, let's see if those help :) I'll add you as a reviewer so you can give feedback as well :)
