### ISSUE TITLE
Fix Navbar + Header for all screen sizes

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/activate-rewrite#16]
Mostly mobile does not look good in all sizes:

<img width="380" alt="screen shot 2018-07-03 at 01 31 25" src="https://user-images.githubusercontent.com/330324/42191044-e039a388-7e60-11e8-931e-1d5b7c5df9f5.png">

<img width="1036" alt="screen shot 2018-07-03 at 01 31 38" src="https://user-images.githubusercontent.com/330324/42191047-e322507c-7e60-11e8-9d67-dda92729c36c.png">

Additionally on mobile the menu does not work at all.

**Comment by MichaelKohler** [comment]
If the navigation items get too long, it breaks to the new line in a weird way and moves the content as well:

<img width="1004" alt="screen shot 2018-07-04 at 00 34 39" src="https://user-images.githubusercontent.com/330324/42247659-0de75f34-7f22-11e8-9885-3793f6db00c3.png">

I think we should arrange this better in case the translations are longer than the English ones.

**Comment by kelimuttu** [comment]
Should we make the menu collapsible in mobile? And as for the too long translation, we can adapt the text size based on the screen.

**Comment by MichaelKohler** [comment]
> Should we make the menu collapsible in mobile?

I would say so, then we can use the hamburger menu to open it. Doesn't necessarily need to be as ugly as it currently is in production though ;)

**Comment by kelimuttu** [comment]
I fixed the hamburger menu, but couldn't make the button to work. And turned out, bootstrap couldn't work with React because it uses jQuery which is using direct DOM. Will try to use reactstrap https://reactstrap.github.io/

**Comment by MichaelKohler** [comment]
Good idea, I think that would be the way to go anyway, as component based is better than using classes :)

**Comment by kelimuttu** [comment]
PR has been sent for this https://github.com/MichaelKohler/activate-rewrite/pull/24
