### ISSUE TITLE
Header and footer bug in webkit

### ISSUE THREAD

**Issue by kelimuttu** [MichaelKohler/activate-rewrite#26]
Found a couple of bug in webkit view today: 
- The header logo is stretched
<img width="1439" alt="screen shot 2018-07-11 at 23 13 03" src="https://user-images.githubusercontent.com/4922388/42582206-200358fe-8561-11e8-9f1d-a22803281042.png">
- Language switcher in the footer is not aligned in mobile view
<img width="391" alt="screen shot 2018-07-11 at 23 12 37" src="https://user-images.githubusercontent.com/4922388/42582213-283e65ae-8561-11e8-8e25-4fb4006f17df.png">

**Comment by MichaelKohler** [comment]
oh, I see you've addressed that already. Will test in the PR :)
