### ISSUE TITLE
Make direct links work on GitHub Pages

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/activate-rewrite#41]
After #40 is merged, a call to https://rewrite.michaelkohler.info/es/eventguide/ will lead to a 404 as GitHub won't find the file as we're using client side routing GitHub doesn't know anything about. There are workarounds for this, will have a look :)

**Comment by MichaelKohler** [comment]
Will be fixed with #40 as well.

**Comment by kelimuttu** [comment]
This should be ok now.
