### ISSUE TITLE
Language selector is not updated for locale URLs

### ISSUE THREAD

**Issue by Josexv1** [MichaelKohler/activate-rewrite#45]
The language selector at the bottom is not persistent, if you set it to `es` and go to a `en-US` link it will stay in Spanish but with the option in `en-US`.

Also if you refresh the website, it will be in English.

![screenshot 38](https://user-images.githubusercontent.com/12077848/43036434-ed941a5e-8ccf-11e8-87f8-6d3926d3fc79.png)

**Comment by Josexv1** [comment]
Sure, i forgot to put the steps to reproduce.

1. Set the language to es
2. go to this link: https://rewrite.michaelkohler.info/es/eventguide/

Result: The language is `es` as defined in the URL. But, as the language is not preserved it will show `en-US`

**Comment by MichaelKohler** [comment]
Thanks. Yep, that's a bug!
